# Generated by Django 3.2.7 on 2022-03-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='uploads/business/')),
                ('contact_tel', models.CharField(blank=True, max_length=80, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visited', models.BooleanField(default=False)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('to_be_visited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('types', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('value', models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10)),
                ('business_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedBusiness', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/details')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('livraison', models.BooleanField(default=False)),
                ('favoris', models.BooleanField(default=False)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='business.business')),
            ],
            options={
                'ordering': ('-prix',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='business.Comment'),
        ),
        migrations.AddField(
            model_name='business',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='business.type'),
        ),
    ]
