# Generated by Django 3.2.7 on 2022-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
